### ISSUE TITLE
error when playing

### ISSUE THREAD

**Issue by fishtez** [fishtez/blackjack#2]
i tried playing the game. the second time i selected hit, it took me back to the main menu.

![game end error](https://cloud.githubusercontent.com/assets/12114756/7443479/c2703fa0-f101-11e4-8ed0-d635931ee36c.png)

**Comment by DavidL47** [comment]
i think it took you back to the main menu because i haven't changed it to
allow you to use lower case h not sure also don't really have an algorithm
for it, i coded as i was thinking and  i just did this as public for now, i
think Zubeir said hes doing the class in public for now until we get
everything working then we will change everything

**Comment by fishtez** [comment]
it's going to be more difficult if we code everything with the variables in public, since we'll have to go back and change almost everything to use the proper member functions once they're added. the professor said we definitely can't have everything public, so it's going to make more work if we have to go back and fix it. it'll change a lot of the boolean expressions within the play function.

**Comment by fishtez** [comment]
old version
